name: 'Environment Indicator Loft UX'
description: 'An alternative indicator UX by In the Loft Studios.'
package: Development
type: module
core_version_requirement: '>=8'
version: 1.3.9
dependencies:
  - 'drupal:environment_indicator'
author: aklump
