<?php

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_library_info_alter().
 */
function environment_indicator_loft_library_info_alter(&$libraries, $extension) {

  // Remove toolbar color changing stuff.
  unset($libraries['drupal.environment_indicator']['js']['js/environment_indicator.js']);
  unset($libraries['drupal.environment_indicator']['js']['js/color.js']);

  // Remove the default CSS.
  unset($libraries['drupal.environment_indicator']['css']['component']['css/environment_indicator.css']);

  // Add our custom CSS.
  $new_path = '/' . drupal_get_path('module', 'environment_indicator_loft');
  $libraries['drupal.environment_indicator']['css']['component'][$new_path . '/css/environment_indicator.css'] = [];
  $libraries['drupal.environment_indicator']['js'][$new_path . '/js/environment_indicator_loft.js'] = [];
  $libraries['drupal.environment_indicator']['dependencies'][] = 'core/jquery';
  $libraries['drupal.environment_indicator']['dependencies'][] = 'core/jquery.once';
}

/**
 * Implements hook_theme_registry_alter().
 */
function environment_indicator_loft_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['environment_indicator'])) {
    $theme_registry['environment_indicator']['path'] = drupal_get_path('module', 'environment_indicator_loft') . '/templates';
  }
}

/**
 * Implements hook_preprocess_THEME().
 */
function environment_indicator_loft_preprocess_environment_indicator(&$vars) {
  $element = $vars['element'];
  $vars['color'] = new Attribute([
    'style' => implode(';', [
      'color:' . $element['#fg_color'],
      'background-color:' . $element['#bg_color'],
    ]),
  ]);
  $vars['branch'] = _environment_indicator_loft_git_branch();
}

/**
 * Get the current Git branch.
 *
 * @return string
 *   The git branch of the Drupal root.
 */
function _environment_indicator_loft_git_branch() {
  static $git_branch;
  if ($git_branch === NULL) {
    $git_branch = exec('cd ' . \Drupal::root() . ' && git rev-parse --abbrev-ref HEAD', $git);
    \Drupal::moduleHandler()->alter('loft_deploy_git_branch', $git_branch);
  }

  return $git_branch;
}
