name: 'Environment Indicator Loft'
description: 'Alters the visual to emulate the deprecated Loft Deploy module.'
package: 'In the Loft Studios'
type: module
core: 8.x
version: 8.x-1.0
dependencies:
  - 'drupal:environment_indicator'
author: aklump
