<?php

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_library_info_alter().
 */
function environment_indicator_loft_library_info_alter(&$libraries, $extension) {
  unset($libraries['drupal.environment_indicator']['css']['component']['css/environment_indicator.css']);
  $new_path = '/' . drupal_get_path('module', 'environment_indicator_loft') . '/css/environment_indicator.css';
  $libraries['drupal.environment_indicator']['css']['component'][$new_path] = [];
}

/**
 * Implements hook_theme_registry_alter().
 */
function environment_indicator_loft_theme_registry_alter(&$theme_registry) {
  if (isset($theme_registry['environment_indicator'])) {
    $theme_registry['environment_indicator']['path'] = drupal_get_path('module', 'environment_indicator_loft') . '/templates';
  }
}

/**
 * Implements hook_preprocess_THEME().
 */
function environment_indicator_loft_preprocess_environment_indicator(&$vars) {
  $element = $vars['element'];
  $vars['color'] = new Attribute([
    'style' => implode(';', [
      'color:' . $element['#fg_color'],
      'background-color:' . $element['#bg_color'],
    ]),
  ]);
}
