name: 'Environment Indicator Loft UX'
description: 'An alternative indicator UX by In the Loft Studios.'
package: Development
type: module
core: 8.x
version: 8.x-1.0.18
dependencies:
  - 'drupal:environment_indicator'
author: aklump
